/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coffeemachine;

import java.io.IOException;

import org.json.JSONException;

import com.coffeemachine.services.CoffeeMachineService;
import com.coffeemachine.services.InventoryService;
import com.coffeemachine.services.JsonParserService;

/**
 * This is the main class of the CoffeeMachine
 * 
 * @author pritampallab
 *
 */
public class App {

	/**
	 * In order to run the main we need to provide the input json file name by the
	 * command line arguments
	 * 
	 * @param args
	 * @throws Exception
	 */
	public static void main(String[] args) throws Exception {
		// These are the two fundamental services of the coffee machines
		InventoryService inventoryService = new InventoryService();
		CoffeeMachineService coffeeMachineService = new CoffeeMachineService();
		try {
			// Reading the input JSON
			JsonParserService jsonParserService = new JsonParserService(args[0]);

			// Adding the items to the inventory
			inventoryService.addItemListToInventory(jsonParserService.getInventoryItems());

			// Adding the beverages orders to the coffee machine memory
			coffeeMachineService.takeOrders(jsonParserService.getBeverages());

			// Configuring the coffee machine
			coffeeMachineService.configure(jsonParserService.getOutletsCount());

			// Processing the orders in parallel
			coffeeMachineService.processOrders();
		} catch (JSONException jSONException) {

			// The input json is incorrect
			System.out.println("Incorrect JSON format");
		} catch (IOException iOException) {

			// The file is not found
			System.out.println("File is not found");
		}

	}
}
