/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coffeemachine;

import org.junit.Test;

import com.coffeemachine.services.CoffeeMachineService;
import com.coffeemachine.services.InventoryService;
import com.coffeemachine.services.JsonParserService;

import static org.junit.Assert.*;

import java.io.IOException;

import org.json.JSONException;

/**
 * This is the test class
 * 
 * @author pritampallab
 *
 */
public class AppTest {
	/**
	 * Test Number 1
	 */
	@Test
	public void exampleTest() {
		InventoryService inventoryService = new InventoryService();
		CoffeeMachineService coffeeMachineService = new CoffeeMachineService();
		try {
			JsonParserService jsonParserService = new JsonParserService("test1.json");
			inventoryService.addItemListToInventory(jsonParserService.getInventoryItems());
			coffeeMachineService.takeOrders(jsonParserService.getBeverages());
			coffeeMachineService.configure(jsonParserService.getOutletsCount());
			coffeeMachineService.processOrders();
		} catch (JSONException jSONException) {
			System.out.println("Incorrect JSON format");
		} catch (IOException iOException) {
			System.out.println("File is not found");
		} catch (InterruptedException e) {
			System.out.println(e);
		}
		assertEquals(true, true);
	}

	/**
	 * Test Number 2
	 */
	@Test
	public void exampleTest2() {
		InventoryService inventoryService = new InventoryService();
		CoffeeMachineService coffeeMachineService = new CoffeeMachineService();
		try {
			JsonParserService jsonParserService = new JsonParserService("test2.json");
			inventoryService.addItemListToInventory(jsonParserService.getInventoryItems());
			coffeeMachineService.takeOrders(jsonParserService.getBeverages());
			coffeeMachineService.configure(jsonParserService.getOutletsCount());
			coffeeMachineService.processOrders();
		} catch (JSONException jSONException) {
			System.out.println("Incorrect JSON format");
		} catch (IOException iOException) {
			System.out.println("File is not found");
		} catch (InterruptedException e) {
			System.out.println(e);
		}
		assertEquals(true, true);
	}

	/**
	 * Test Number 3
	 */
	@Test
	public void exampleTest3() {
		InventoryService inventoryService = new InventoryService();
		CoffeeMachineService coffeeMachineService = new CoffeeMachineService();
		try {
			JsonParserService jsonParserService = new JsonParserService("test3.json");
			inventoryService.addItemListToInventory(jsonParserService.getInventoryItems());
			coffeeMachineService.takeOrders(jsonParserService.getBeverages());
			coffeeMachineService.configure(jsonParserService.getOutletsCount());
			coffeeMachineService.processOrders();
		} catch (JSONException jSONException) {
			System.out.println("Incorrect JSON format");
		} catch (IOException iOException) {
			System.out.println("File is not found");
		} catch (InterruptedException e) {
			System.out.println(e);
		}
		assertEquals(true, true);
	}
}
